name: PyTest

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "trace-parsing-and-modeling-spark"
      - "dev"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Cache the pip directory instead of the virtual environment
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('udao/requirements-cpu.txt') }}-${{ hashFiles('udao/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r udao/requirements-cpu.txt

      - name: Run Pytest
        run: |
          pytest traces
#          pytest udao
